"""
Django settings for vinyles project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Se agregó el import de os
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--byrce+$%&e!-0xl%$40w=-hry&3oc09wvsyd^9l9bk-g0%h20'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Se agregó gestion
    'gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vinyles.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Se agregó el debug
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vinyles.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # O 'django.db.backends.mysql' si usas MySQL
        'NAME': 'vinyles',
        'USER': 'root',
        'PASSWORD': 'GRUPO42025',
        'HOST': 'localhost',  # O la dirección IP de tu servidor de MariaDB
        'PORT': '3307',  # O el puerto en el que se ejecuta MariaDB (por defecto es 3306)
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            'read_default_file': os.path.join(BASE_DIR, 'my.cnf'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co' # o 'es-es', 'es-ar', 'es-mx', etc.

TIME_ZONE = 'UTC' # O tu zona horaria

USE_I18N = True

USE_L10N = True # Importante para que los formatos localizados funcionen

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Se agregó la ruta de los archivos estáticos
STATICFILES_DIRS = [
    os.path.join(
        BASE_DIR / "static",
    ),
] # Todos los archivos estáticos se busquen dentro de la carpeta "static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DIRECCIONARÁ LAS FOTOS A LA CARPETA "static/images/fotosusuario"
MEDIA_ROOT = os.path.join(BASE_DIR, 'static', 'images', 'fotosusuario')
MEDIA_URL = '/fotos/' # La URL para acceder a las fotos será /fotos/ dentro de la dirección de arriba.

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'