# Generated by Django 5.2.1 on 2025-06-04 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_residencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
