# Generated by Django 5.2.4 on 2025-07-07 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicacion',
            unique_together=set(),
        ),
    ]
