# Generated by Django 5.2.4 on 2025-07-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_residencia',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número de Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crud',
            name='clase',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Clase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crud',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='url_destino',
            field=models.CharField(blank=True, default='', help_text='URL a la que debe dirigir la notificación.', max_length=255),
            preserve_default=False,
        ),
    ]
