# Generated by Django 5.2.2 on 2025-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_clienteprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Género')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='clienteprofile',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='generos_favoritos',
            field=models.ManyToManyField(blank=True, to='gestion.genero', verbose_name='Géneros Favoritos'),
        ),
    ]
