# Generated by Django 5.2.4 on 2025-07-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_pedido_costo_envio_pedido_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='gestion.producto', verbose_name='Producto del Catálogo'),
        ),
    ]
