# Generated by Django 5.2.4 on 2025-07-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_publicacion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad_residencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad de Residencia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_extra',
            field=models.CharField(blank=True, max_length=255, verbose_name='Información Adicional Dirección'),
        ),
    ]
