# Generated by Django 5.2.2 on 2025-06-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cliente_delete_clienteprofile'),
    ]

    operations = [
    # Eliminamos el migrations.RunSQL manual.
    # Dejamos solo la operación AlterModelTable que Django generó.
    # Esta operación se encargará de renombrar la tabla en la BD
    # y actualizar el estado de Django.
        migrations.AlterModelTable(
            name='cliente', # El nombre de tu modelo en Python (Cliente)
            table='cliente', # El nuevo nombre de la tabla en la base de datos
        ),
    ]
