# Generated by Django 5.2.2 on 2025-06-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crud',
            options={'verbose_name': 'Crud', 'verbose_name_plural': 'Cruds'},
        ),
        migrations.AlterField(
            model_name='crud',
            name='clase',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='crud',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='crud',
            table='crud',
        ),
        migrations.AlterModelTable(
            name='genero',
            table='genero',
        ),
    ]
