# Generated by Django 5.2.2 on 2025-06-12 03:02

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_crud_options_alter_crud_clase_alter_crud_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crud',
            options={'verbose_name': 'CRUD', 'verbose_name_plural': 'CRUDS'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=gestion.models.user_directory_path, verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='crud',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='crud',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_crud/', verbose_name='Foto'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='crud',
            table='cruds',
        ),
        migrations.AlterModelTable(
            name='genero',
            table='generos',
        ),
    ]
