# Generated by Django 5.2.3 on 2025-06-17 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_crud_options_alter_cliente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Artista')),
                ('informacion', models.TextField(blank=True, null=True, verbose_name='Información del Artista')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='artistas/', verbose_name='Foto del Artista')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'db_table': 'artistas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['pais', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Medio de Pago')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'db_table': 'medios_de_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Productor')),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'db_table': 'productores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Canción')),
                ('duracion', models.DurationField(blank=True, null=True, verbose_name='Duración (ej: 00:03:46)')),
                ('artistas', models.ManyToManyField(blank=True, related_name='canciones_realizadas', to='gestion.artista', verbose_name='Artistas')),
                ('generos', models.ManyToManyField(blank=True, related_name='canciones_genero', to='gestion.genero', verbose_name='Géneros')),
                ('productores', models.ManyToManyField(blank=True, related_name='canciones_producidas', to='gestion.productor', verbose_name='Productores')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'db_table': 'canciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Ciudad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='gestion.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
                'ordering': ['departamento', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='medios_de_pago_guardados',
            field=models.ManyToManyField(blank=True, db_table='cliente_medio_de_pago', to='gestion.mediodepago', verbose_name='Medios de Pago Guardados'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='gestion.pais', verbose_name='País'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Pedido')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total del Pedido')),
                ('direccion_envio', models.CharField(max_length=255, verbose_name='Dirección de Envío')),
                ('ciudad_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_enviados_aqui', to='gestion.ciudad', verbose_name='Ciudad de Envío')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='gestion.cliente', verbose_name='Cliente')),
                ('medio_de_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_pagados_con', to='gestion.mediodepago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-fecha', 'cliente'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto/Álbum')),
                ('lanzamiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Producto')),
                ('discografica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Compañía Discográfica')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='productos_portadas/', verbose_name='Imagen de Portada')),
                ('artistas', models.ManyToManyField(related_name='productos', to='gestion.artista', verbose_name='Artista(s) Principal(es)')),
                ('genero_principal', models.ManyToManyField(blank=True, related_name='productos_principales', to='gestion.genero', verbose_name='Género(s) Principal(es) del Álbum')),
            ],
            options={
                'verbose_name': 'Producto (Vinilo/Álbum)',
                'verbose_name_plural': 'Productos (Vinilos/Álbumes)',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario en el Momento de la Compra')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='gestion.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_de_pedido', to='gestion.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto del Pedido',
                'verbose_name_plural': 'Productos del Pedido',
                'db_table': 'pedido_productos',
                'ordering': ['pedido', 'producto'],
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(related_name='en_pedidos', through='gestion.PedidoProducto', to='gestion.producto', verbose_name='Productos en el Pedido'),
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del Caso')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20, verbose_name='Estado del Caso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_soporte', to='gestion.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'db_table': 'tickets_soporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pista', models.PositiveIntegerField(verbose_name='Número de Pista')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apariciones_en_productos', to='gestion.cancion', verbose_name='Canción')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='gestion.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Canción en Producto',
                'verbose_name_plural': 'Canciones en Productos',
                'db_table': 'producto_canciones',
                'ordering': ['producto', 'numero_pista'],
                'unique_together': {('producto', 'cancion'), ('producto', 'numero_pista')},
            },
        ),
    ]
