# Generated by Django 5.2.3 on 2025-06-18 02:40

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_artista_departamento_mediodepago_pais_productor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='foto',
            field=models.ImageField(default='artistas/default/default_avatar.png', upload_to='artistas/', verbose_name='Foto del Artista'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='informacion',
            field=models.TextField(default='', verbose_name='Información del Artista'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil/default/default_avatar.png', null=True, upload_to=gestion.models.user_directory_path, verbose_name='Foto de Perfil'),
        ),
    ]
