# Generated by Django 5.2.3 on 2025-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_artista_foto_alter_artista_informacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción del Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='discografica',
            field=models.CharField(default='Desconocida', max_length=200, verbose_name='Compañía Discográfica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_portada',
            field=models.ImageField(upload_to='productos_portadas/', verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lanzamiento',
            field=models.DateField(default='2000-01-01', verbose_name='Fecha de Lanzamiento'),
            preserve_default=False,
        ),
    ]
