# Generated by Django 5.2.3 on 2025-06-22 19:58

import django.db.models.deletion
import gestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_producto_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/', verbose_name='Foto del Artista'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='informacion',
            field=models.TextField(blank=True, default='', verbose_name='Información del Artista'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=gestion.models.user_directory_path, verbose_name='Foto de Perfil'),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Código de Restablecimiento de Contraseña',
                'verbose_name_plural': 'Códigos de Restablecimiento de Contraseña',
                'db_table': 'password_reset_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
