# Generated by Django 5.2.3 on 2025-06-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_artista_foto_alter_artista_informacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='discogs_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID de Discogs'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='discogs_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID de Discogs'),
        ),
        migrations.AddField(
            model_name='productor',
            name='discogs_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID de Discogs'),
        ),
    ]
