# Generated by Django 5.2.3 on 2025-06-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_artista_discogs_id_cancion_discogs_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='foto',
            field=models.ImageField(blank=True, default='generos/default/default_genero.png', null=True, upload_to='generos/', verbose_name='Foto del Género'),
        ),
    ]
