# Generated by Django 5.2.3 on 2025-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_genero_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_portada',
            field=models.ImageField(default='albumes/default/default_album.png', upload_to='productos_portadas/', verbose_name='Imagen de Portada'),
        ),
    ]
