# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Para proyectos de Python con requirements.txt
    directory: "/" # La raíz del repositorio, donde está tu requirements.txt
    schedule:
      interval: "weekly"
    # Opcional: Limita el número de PRs abiertos por Dependabot a 5 para no saturar.
    open-pull-requests-limit: 5
    # Opcional: Asigna automáticamente a un revisor (cambia 'stebanpls' por tu usuario o el de un compañero).
    reviewers:
      - "Aerizzu"
      - "Angtty"
      - "CristiamSkull"
      - "Koshka_Nikke"
      - "stebanpls"
    # Opcional: Añade una etiqueta a los PRs para una mejor organización.
    labels:
      - "dependencies"
    # Opcional: Agrupa las actualizaciones de paquetes relacionados en un solo Pull Request.
    groups:
      # Nombra el grupo como quieras, por ejemplo "django-framework".
      django-framework:
        patterns:
          - "django"
          - "django-*"
