# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Elimina espacios en blanco innecesarios al final de las líneas.
      - id: trailing-whitespace
      # Asegura que todos los archivos terminen con una sola línea en blanco.
      - id: end-of-file-fixer
      # Revisa que los archivos YAML (como este) tengan una sintaxis válida.
      - id: check-yaml
      # Evita que se suban archivos con marcadores de conflictos de merge.
      - id: check-merge-conflict
      # Evita que accidentalmente se suban archivos muy grandes al repositorio.
      # Si usas Git LFS (ver más abajo), este hook sigue siendo útil para
      # recordarte qué archivos deberían estar en LFS.
      - id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Asegúrate de usar una versión reciente de ruff
    rev: v0.12.2
    hooks:
      # Ejecuta el linter y auto-corrige lo que pueda
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Ejecuta el formateador de código
      - id: ruff-format

# -   repo: https://github.com/djlint/djlint
#     rev: v1.34.1
#     hooks:
#       - id: djlint-reformat-django
#
-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.6 # Esta es la última versión estable
    hooks:
      - id: bandit
        args: ["-s", "B101"] # Ignorar la comprobación de 'assert'

-   repo: https://github.com/pypa/pip-audit
    rev: v2.9.0 # Esta es la última versión estable
    hooks:
      - id: pip-audit
        name: Pip-Audit - Check for vulnerabilities
        args: ["-r", "requirements.txt", "--no-deps"]
        # El hook se ejecutará automáticamente cuando cambie requirements.txt
