# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Elimina espacios en blanco innecesarios al final de las líneas.
      - id: trailing-whitespace
      # Asegura que todos los archivos terminen con una sola línea en blanco.
      - id: end-of-file-fixer
      # Revisa que los archivos YAML (como este) tengan una sintaxis válida.
      - id: check-yaml
      # Evita que se suban archivos con marcadores de conflictos de merge.
      - id: check-merge-conflict
      # Evita que accidentalmente se suban archivos muy grandes al repositorio.
      # Si usas Git LFS (ver más abajo), este hook sigue siendo útil para
      # recordarte qué archivos deberían estar en LFS.
      - id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Asegúrate de usar una versión reciente de ruff
    rev: v0.5.0
    hooks:
      # Ejecuta el linter y auto-corrige lo que pueda
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Ejecuta el formateador de código
      - id: ruff-format

-   repo: local
    hooks:
      - id: python-manage-py-check-migrations
        name: Django - Check for missing migrations
        # Usamos 'check --migrations' para ser más específicos con el propósito del hook.
        # El comando correcto es 'makemigrations --check'.
        entry: ../.venv/Scripts/python.exe manage.py makemigrations --check
        # Usamos 'system' para que el hook se ejecute en tu entorno virtual (.venv)
        # y tenga acceso a TODAS las dependencias de tu proyecto.
        language: system
        types: [python]
        pass_filenames: false

# -   repo: https://github.com/djlint/djlint
#     rev: v1.34.1
#     hooks:
#       - id: djlint-reformat-django
#
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-s", "B101"] # Ignorar la comprobación de 'assert'
