[tool.ruff]
# Configuración global para ruff. Aplica tanto al linter como al formateador.
line-length = 120
# Excluye directorios que no se deben revisar.
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "migrations",
    "venv", # Añadido por si acaso
]

[tool.ruff.lint]
# Habilita las reglas de Pyflakes (F), pycodestyle (E, W), isort (I) y Bugbear (B).
select = ["E", "F", "W", "I", "B", "DJ", "UP", "C90"]
# Ya no ignoramos E501. Ruff lo comprobará contra el nuevo line-length.
ignore = ["E501"] # <-- ¡Añade esta línea! Le dice al linter que ignore las líneas largas.

[tool.ruff.lint.isort]
# Le dice a isort que tus apps de Django son "first-party" para agrupar los imports correctamente.
known-first-party = ["gestion", "vinyles"]

[tool.ruff.format]
# Habilita el formateador de código (similar a Black) para mantener un estilo consistente.
preview = true
